name: Build Spore Mod Browser and deploy to GitHub Pages

env:
  PUBLISH_PATH: SporeCommunity.ModBrowser.Blazor/bin/Release/net5.0/publish/wwwroot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Publish with .NET
      run: dotnet publish -c Release -p:BlazorEnableCompression=false
      working-directory: ./SporeCommunity.ModBrowser.Blazor

    - name: Add 404 redirect file
      run: wget -P ${{ env.PUBLISH_PATH }} "https://raw.githubusercontent.com/rafgraph/spa-github-pages/gh-pages/404.html"

    - name: Add readme file
      run: wget -P ${{ env.PUBLISH_PATH }} "https://gist.githubusercontent.com/KyleNanakdewa/b2dece4553f9900090fe3ce271d73048/raw/474ada9e5805ade145bcef79cf3d0c4bc0ecac2a/README.md"

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_PATH }}/index.html
        base_href: /ModBrowser/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.PUBLISH_PATH }}
