name: Build Spore Mod Browser and deploy to GitHub Pages

env:
  PUBLISH_PATH: bin/Release/netstandard2.1/publish/wwwroot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Publish with .NET
      run: dotnet publish -c Release -p:BlazorEnableCompression=false

    - name: Add 404 redirect file
      run: wget -P ${{ env.PUBLISH_PATH }} "https://raw.githubusercontent.com/rafgraph/spa-github-pages/gh-pages/404.html"

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_PATH }}/index.html
        base_href: /ModBrowser/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        publish_dir: ${{ env.PUBLISH_PATH }}
